"""切片候选、语义边界与收播识别共享的稳定策略。"""

from __future__ import annotations

import re

from autoslice.analysis.danmaku import DANMAKU_WINDOW

FACADE_EXPORTS = {
    "_UNCUTTABLE_CONTENT_KEYWORDS": "UNCUTTABLE_CONTENT_KEYWORDS",
    "CLIP_MANUAL_REVIEW_MIN_STARS": "CLIP_MANUAL_REVIEW_MIN_STARS",
    "CLIP_MIN_INTEREST_SCORE": "CLIP_MIN_INTEREST_SCORE",
    "CLIP_REVIEW_BATCH_SIZE": "CLIP_REVIEW_BATCH_SIZE",
    "CLIP_REVIEW_RETRY_BATCH_SIZE": "CLIP_REVIEW_RETRY_BATCH_SIZE",
    "OUTRO_TRIGGER_JOIN_GAP_SEC": "OUTRO_TRIGGER_JOIN_GAP_SEC",
    "OUTRO_VARIANT_FAREWELL_AFTER_SEC": "OUTRO_VARIANT_FAREWELL_AFTER_SEC",
    "OUTRO_VARIANT_FAREWELL_BEFORE_SEC": "OUTRO_VARIANT_FAREWELL_BEFORE_SEC",
    "SC_CONTEXT_LOOKBACK_SEC": "SC_CONTEXT_LOOKBACK_SEC",
    "SC_FALLBACK_GIFT_LOOKBACK_SEC": "SC_FALLBACK_GIFT_LOOKBACK_SEC",
    "SC_TRIGGER_KEYWORDS": "SC_TRIGGER_KEYWORDS",
    "THANKS_TRIGGER_RE": "THANKS_TRIGGER_RE",
    "TOPIC_AI_FOCUS_EDGE_POST_CONTEXT_SEC": "TOPIC_AI_FOCUS_EDGE_POST_CONTEXT_SEC",
    "TOPIC_AI_FOCUS_EDGE_PRE_CONTEXT_SEC": "TOPIC_AI_FOCUS_EDGE_PRE_CONTEXT_SEC",
    "TOPIC_AI_FOCUS_NATURAL_POST_BOUNDARY_SEC": (
        "TOPIC_AI_FOCUS_NATURAL_POST_BOUNDARY_SEC"
    ),
    "TOPIC_AI_FOCUS_NATURAL_PRE_BOUNDARY_SEC": (
        "TOPIC_AI_FOCUS_NATURAL_PRE_BOUNDARY_SEC"
    ),
    "TOPIC_AI_FOCUS_POST_CONTEXT_SEC": "TOPIC_AI_FOCUS_POST_CONTEXT_SEC",
    "TOPIC_AI_FOCUS_PRE_CONTEXT_SEC": "TOPIC_AI_FOCUS_PRE_CONTEXT_SEC",
    "TOPIC_BOUNDARY_EVIDENCE_FORWARD_SEARCH_SEC": (
        "TOPIC_BOUNDARY_EVIDENCE_FORWARD_SEARCH_SEC"
    ),
    "TOPIC_BOUNDARY_EVIDENCE_FORWARD_SEC": "TOPIC_BOUNDARY_EVIDENCE_FORWARD_SEC",
    "TOPIC_BOUNDARY_EVIDENCE_LOOKBACK_SEC": "TOPIC_BOUNDARY_EVIDENCE_LOOKBACK_SEC",
    "TOPIC_BOUNDARY_EVIDENCE_MIN_SCORE": "TOPIC_BOUNDARY_EVIDENCE_MIN_SCORE",
    "TOPIC_BOUNDARY_FORWARD_SHIFT_MAX_SEC": "TOPIC_BOUNDARY_FORWARD_SHIFT_MAX_SEC",
    "TOPIC_DIRECT_SLICE_MAX_SEC": "TOPIC_DIRECT_SLICE_MAX_SEC",
    "TOPIC_FOCUS_POST_SEC": "TOPIC_FOCUS_POST_SEC",
    "TOPIC_FOCUS_PRE_SEC": "TOPIC_FOCUS_PRE_SEC",
    "TOPIC_HARD_TRANSITION_GAP_SEC": "TOPIC_HARD_TRANSITION_GAP_SEC",
    "TOPIC_LEAD_IN_LOOKBACK_SEC": "TOPIC_LEAD_IN_LOOKBACK_SEC",
    "TOPIC_LEAD_IN_RECOVERY_MIN_SEC": "TOPIC_LEAD_IN_RECOVERY_MIN_SEC",
    "TOPIC_MAX_CLIP_SEC": "TOPIC_MAX_CLIP_SEC",
    "TOPIC_MAX_REPAIRED_REPORT_SEC": "TOPIC_MAX_REPAIRED_REPORT_SEC",
    "TOPIC_MIN_CLIP_SEC": "TOPIC_MIN_CLIP_SEC",
    "TOPIC_MIN_REPORT_SEC": "TOPIC_MIN_REPORT_SEC",
    "TOPIC_NATURAL_BOUNDARY_POST_MAX_SEC": "TOPIC_NATURAL_BOUNDARY_POST_MAX_SEC",
    "TOPIC_NATURAL_BOUNDARY_PRE_MAX_SEC": "TOPIC_NATURAL_BOUNDARY_PRE_MAX_SEC",
    "TOPIC_POST_CONTEXT_SEC": "TOPIC_POST_CONTEXT_SEC",
    "TOPIC_PRE_CONTEXT_SEC": "TOPIC_PRE_CONTEXT_SEC",
    "TOPIC_REFERENCE_END_TOLERANCE_SEC": "TOPIC_REFERENCE_END_TOLERANCE_SEC",
    "TOPIC_RELEVANT_CONTINUATION_GAP_SEC": "TOPIC_RELEVANT_CONTINUATION_GAP_SEC",
    "TOPIC_REQUIRED_CONTEXT_OVERFLOW_SEC": "TOPIC_REQUIRED_CONTEXT_OVERFLOW_SEC",
    "TOPIC_REVIEW_FOCUS_MAX_SEC": "TOPIC_REVIEW_FOCUS_MAX_SEC",
}


# 数量不设配额；候选只有独立达到投稿价值门槛才进入切片复核。
CLIP_MIN_INTEREST_SCORE = 75
CLIP_MANUAL_REVIEW_MIN_STARS = 4
CLIP_REVIEW_BATCH_SIZE = 3
CLIP_REVIEW_RETRY_BATCH_SIZE = 2

# 仅描述无有效主播内容、背景媒体或分析兜底的话题不能直接进入切片。
UNCUTTABLE_CONTENT_KEYWORDS = (
    "未发言",
    "仅播放",
    "只是播放",
    "游戏角色对话语音",
    "背景语音",
    "游戏画面/语音",
    "具体内容不清晰",
    "字幕识别较碎",
    "未形成稳定可切片主题",
    "暂不标记为自动切片",
    "无有效讲话",
    "全是沉默",
    "全是音乐",
    "机械复读",
    "游戏开头动画",
)

# 通用候选和 AI 已确认语义核心使用不同的前后文预算。
TOPIC_PRE_CONTEXT_SEC = 45
TOPIC_POST_CONTEXT_SEC = 60
TOPIC_MIN_CLIP_SEC = 75
TOPIC_MAX_CLIP_SEC = 240
TOPIC_REQUIRED_CONTEXT_OVERFLOW_SEC = 60
TOPIC_REVIEW_FOCUS_MAX_SEC = 180
TOPIC_DIRECT_SLICE_MAX_SEC = TOPIC_REVIEW_FOCUS_MAX_SEC
TOPIC_FOCUS_PRE_SEC = 0
TOPIC_FOCUS_POST_SEC = DANMAKU_WINDOW
TOPIC_NATURAL_BOUNDARY_PRE_MAX_SEC = 30
TOPIC_NATURAL_BOUNDARY_POST_MAX_SEC = 45
TOPIC_AI_FOCUS_PRE_CONTEXT_SEC = 20
TOPIC_AI_FOCUS_POST_CONTEXT_SEC = 20
TOPIC_AI_FOCUS_EDGE_PRE_CONTEXT_SEC = 45
TOPIC_AI_FOCUS_EDGE_POST_CONTEXT_SEC = 60
TOPIC_AI_FOCUS_NATURAL_PRE_BOUNDARY_SEC = 5
TOPIC_AI_FOCUS_NATURAL_POST_BOUNDARY_SEC = 10
TOPIC_LEAD_IN_RECOVERY_MIN_SEC = 90
TOPIC_LEAD_IN_LOOKBACK_SEC = 180
TOPIC_BOUNDARY_EVIDENCE_LOOKBACK_SEC = 90
TOPIC_BOUNDARY_EVIDENCE_FORWARD_SEC = 60
TOPIC_BOUNDARY_FORWARD_SHIFT_MAX_SEC = 30
TOPIC_BOUNDARY_EVIDENCE_MIN_SCORE = 10
TOPIC_HARD_TRANSITION_GAP_SEC = 10
TOPIC_RELEVANT_CONTINUATION_GAP_SEC = 50
TOPIC_BOUNDARY_EVIDENCE_FORWARD_SEARCH_SEC = 180
TOPIC_REFERENCE_END_TOLERANCE_SEC = 90
TOPIC_MIN_REPORT_SEC = 60
TOPIC_MAX_REPAIRED_REPORT_SEC = 180

# SC/礼物仅用于恢复真实前因，不作为机械切片触发器。
SC_CONTEXT_LOOKBACK_SEC = 180
SC_FALLBACK_GIFT_LOOKBACK_SEC = 15
SC_TRIGGER_KEYWORDS = (
    "sc",
    "s c",
    "super chat",
    "superchat",
    "醒目留言",
    "醒目",
    "付费留言",
    "舰长",
    "上舰",
    "总督",
    "提督",
    "舰团",
    "礼物",
    "打赏",
    "投喂",
    "爱心抱枕",
    "告白花束",
    "棉花糖",
    "牛哇牛哇",
    "充电",
)
THANKS_TRIGGER_RE = re.compile(
    r"(谢谢|感谢|谢[谢了]?|多谢).{0,24}(送|的|老板|老公|礼物|留言|支持)"
)

# 收播变体必须与附近告别证据共同命中。
OUTRO_TRIGGER_JOIN_GAP_SEC = 8
OUTRO_VARIANT_FAREWELL_BEFORE_SEC = 30
OUTRO_VARIANT_FAREWELL_AFTER_SEC = 180
