"""
话题分析 + 智能切片引擎

流水线: FunASR转录 → 弹幕密度分析 → SRT分块 → DeepSeek Pro分析 → 报告 + 切片标记

用法:
  from autoslice.topic_engine import run_pipeline
  result = run_pipeline(flv_path, ass_path, progress_callback=cb)
  # result: {"report": "...", "clip_marks": [...], "json_path": "..."}
"""

import os

from autoslice.analysis import candidates as candidate_analysis
from autoslice.analysis import danmaku as danmaku_analysis
from autoslice.analysis import timeline as timeline_analysis
from autoslice.analysis import titles as title_analysis
from autoslice import reporting as reporting_service
from autoslice import slicing as slicing_service
from autoslice import pipeline as pipeline_service
from autoslice.llm import transport as llm_gateway
from autoslice.llm.prompts import (
    ClipCandidatePromptEvidence as _ClipCandidatePromptEvidence,
    ManualTopicPromptEvidence as _ManualTopicPromptEvidence,
    PromptContext as _PromptContext,
    SYSTEM_PROMPT,
    TITLE_HOOK_PROMPT_GUIDE,
    TopicAnalysisPromptEvidence as _TopicAnalysisPromptEvidence,
    build_clip_candidate_review_prompt as _render_clip_candidate_review_prompt,
    build_final_title_generation_prompt as _render_final_title_generation_prompt,
    build_final_title_judge_prompt as _render_final_title_judge_prompt,
    build_manual_topic_enrichment_prompt as _render_manual_topic_enrichment_prompt,
    build_system_prompt as _render_system_prompt,
    build_title_hook_guide as _render_title_hook_guide,
    build_title_style_prompt as _render_title_style_prompt,
    build_topic_analysis_prompt as _render_topic_analysis_prompt,
)
from autoslice.transcription import service as transcription_service
from autoslice.transcription.contracts import (
    DEFAULT_MAX_PUBLISH_TITLE_CHARS,
    DEFAULT_SUBTITLE_GLOSSARY,
    DEFAULT_SUBTITLE_MAX_CHARS,
    SubtitleTitleServices,
)
from autoslice.artifact_store import (
    ARTIFACT_BUNDLE_SUFFIX,
    ARTIFACT_DATA_DIRNAME,
    ARTIFACT_LAYOUT_VERSION,
    ARTIFACT_QUEUE_DIRNAME,
    UNIFIED_REFINEMENT_QUEUE_JSON,
    UNIFIED_REFINEMENT_QUEUE_MD,
    artifact_bundle_layout as _calculate_artifact_bundle_layout,
    artifact_bundle_stem as _artifact_bundle_stem,
    copy_artifact_file as _copy_artifact_file,
    first_existing_artifact_path as _first_existing_artifact_path,
    load_artifact_json as _load_artifact_json,
    markdown_relative_artifact_link as _markdown_relative_artifact_link,
    rewrite_organized_report_links as _rewrite_organized_report_links,
    seed_artifact_from_legacy as _seed_artifact_from_legacy,
    write_artifact_json as _write_artifact_json,
    write_artifact_text as _write_artifact_text,
)
from autoslice.streamer_profiles import (
    active_streamer_profile,
    current_streamer_profile,
    resolve_streamer_profile,
    streamer_profile_context,
)
from autoslice.runtime_config import OUTPUT_DIR, TIMELINE_DIR


# 转录兼容 façade：所有符号直接绑定唯一 service 对象，禁止本地再实现。
_infer_streamer_name = transcription_service.infer_streamer_name
FUNASR_BATCH_SIZE_SEC = transcription_service.FUNASR_BATCH_SIZE_SEC
FUNASR_CACHE_MODEL_DIR = transcription_service.FUNASR_CACHE_MODEL_DIR
FUNASR_CHECKPOINT_VERSION = transcription_service.FUNASR_CHECKPOINT_VERSION
FUNASR_CHUNK_PRE_CONTEXT_SEC = transcription_service.FUNASR_CHUNK_PRE_CONTEXT_SEC
FUNASR_CHUNK_SEC = transcription_service.FUNASR_CHUNK_SEC
FUNASR_CONTEXTUAL_CACHE_MODEL_DIR = transcription_service.FUNASR_CONTEXTUAL_CACHE_MODEL_DIR
FUNASR_CONTEXTUAL_CACHE_MODEL_DIR_IIC = transcription_service.FUNASR_CONTEXTUAL_CACHE_MODEL_DIR_IIC
FUNASR_CONTEXTUAL_MODEL = transcription_service.FUNASR_CONTEXTUAL_MODEL
FUNASR_CPU_RETRY_DELAY_SEC = transcription_service.FUNASR_CPU_RETRY_DELAY_SEC
FUNASR_DEFAULT_DEVICE = transcription_service.FUNASR_DEFAULT_DEVICE
FUNASR_FOREGROUND_AUDIO_FILTER = transcription_service.FUNASR_FOREGROUND_AUDIO_FILTER
FUNASR_HOTWORD_MAX_CHARS = transcription_service.FUNASR_HOTWORD_MAX_CHARS
FUNASR_HOTWORD_MAX_COUNT = transcription_service.FUNASR_HOTWORD_MAX_COUNT
FUNASR_MODEL = transcription_service.FUNASR_MODEL
FUNASR_NANO_CACHE_ROOTS = transcription_service.FUNASR_NANO_CACHE_ROOTS
FUNASR_NANO_MODEL = transcription_service.FUNASR_NANO_MODEL
FUNASR_PUNC_CACHE_MODEL_DIR = transcription_service.FUNASR_PUNC_CACHE_MODEL_DIR
FUNASR_PUNC_MODEL = transcription_service.FUNASR_PUNC_MODEL
FUNASR_SPK_CACHE_MODEL_DIR = transcription_service.FUNASR_SPK_CACHE_MODEL_DIR
FUNASR_SPK_MODEL = transcription_service.FUNASR_SPK_MODEL
FUNASR_SPK_WEIGHT_FILES = transcription_service.FUNASR_SPK_WEIGHT_FILES
FUNASR_VAD_CACHE_MODEL_DIR = transcription_service.FUNASR_VAD_CACHE_MODEL_DIR
FUNASR_VAD_MODEL = transcription_service.FUNASR_VAD_MODEL
SRT_ABNORMAL_CHARS_PER_SEC = transcription_service.SRT_ABNORMAL_CHARS_PER_SEC
SRT_MAX_ESTIMATED_SEG_SEC = transcription_service.SRT_MAX_ESTIMATED_SEG_SEC
SRT_REPEAT_REPAIR_MIN_ENTRIES = transcription_service.SRT_REPEAT_REPAIR_MIN_ENTRIES
SUBTITLE_LEGACY_REPAIR_MAX_CHARS = transcription_service.SUBTITLE_LEGACY_REPAIR_MAX_CHARS
SUBTITLE_MAX_CHARS = transcription_service.SUBTITLE_MAX_CHARS
SUBTITLE_MAX_DURATION_SEC = transcription_service.SUBTITLE_MAX_DURATION_SEC
SUBTITLE_PAUSE_BREAK_SEC = transcription_service.SUBTITLE_PAUSE_BREAK_SEC
SUBTITLE_TARGET_CHARS = transcription_service.SUBTITLE_TARGET_CHARS
_repair_srt_end_time = transcription_service._repair_srt_end_time
_join_asr_tokens = transcription_service._join_asr_tokens
_strip_asr_subtitle_punctuation = transcription_service._strip_asr_subtitle_punctuation
_normalise_asr_text = transcription_service._normalise_asr_text
_split_subtitle_text_for_display = transcription_service._split_subtitle_text_for_display
_split_timed_subtitle_segment = transcription_service._split_timed_subtitle_segment
_should_hold_subtitle_for_short_clause = transcription_service._should_hold_subtitle_for_short_clause
_segment_timed_tokens = transcription_service._segment_timed_tokens
_segments_from_funasr_result = transcription_service._segments_from_funasr_result
_read_srt_entries = transcription_service._read_srt_entries
export_corrected_srt = transcription_service.export_corrected_srt
_probe_video_duration = transcription_service.probe_video_duration
_prepare_funasr_environment = transcription_service._prepare_funasr_environment
_funasr_model_cache_candidates = transcription_service.funasr_model_cache_candidates
_funasr_nano_cache_candidates = transcription_service._funasr_nano_cache_candidates
_resolve_funasr_model_source = transcription_service.resolve_funasr_model_source
_resolve_funasr_aux_model_source = transcription_service.resolve_funasr_aux_model_source
_resolve_funasr_speaker_model_source = transcription_service.resolve_funasr_speaker_model_source
_funasr_model_runtime_signature = transcription_service._funasr_model_runtime_signature
_funasr_hotwords = transcription_service._funasr_hotwords
_funasr_generate_kwargs = transcription_service._funasr_generate_kwargs
_resolve_funasr_device = transcription_service.resolve_funasr_device
funasr_public_status = transcription_service.funasr_public_status
_load_funasr_model = transcription_service.load_funasr_model
_funasr_checkpoint_path = transcription_service.funasr_checkpoint_path
_funasr_source_fingerprint = transcription_service._funasr_source_fingerprint
_funasr_chunk_fingerprint = transcription_service._funasr_chunk_fingerprint
_funasr_chunk_input_window = transcription_service._funasr_chunk_input_window
_normalise_funasr_result = transcription_service._normalise_funasr_result
_is_valid_funasr_result = transcription_service._is_valid_funasr_result
_primary_speaker_segments = transcription_service._primary_speaker_segments
_is_close_number = transcription_service._is_close_number
_prepare_funasr_checkpoint = transcription_service._prepare_funasr_checkpoint
_write_funasr_checkpoint = transcription_service.write_funasr_checkpoint
_clear_funasr_cuda_cache = transcription_service.clear_funasr_cuda_cache
_dedupe_overlapping_funasr_segments = transcription_service._dedupe_overlapping_funasr_segments
_is_funasr_punctuation = transcription_service._is_funasr_punctuation
_attach_funasr_punctuation_to_tokens = transcription_service._attach_funasr_punctuation_to_tokens
_align_funasr_tokens = transcription_service._align_funasr_tokens
_trim_funasr_tokens_to_core = transcription_service._trim_funasr_tokens_to_core
ensure_srt = transcription_service.ensure_srt
_srt_time = transcription_service.srt_time
_parse_srt_timestamp = transcription_service.parse_srt_timestamp


# 弹幕兼容 façade：解析、峰值和刷屏降权只保留唯一实现。
CLIP_DENSITY_PERCENTILE = danmaku_analysis.CLIP_DENSITY_PERCENTILE
CLIP_DENSITY_RATIO = danmaku_analysis.CLIP_DENSITY_RATIO
CLIP_LOCAL_PEAK_RADIUS_SEC = danmaku_analysis.CLIP_LOCAL_PEAK_RADIUS_SEC
DANMAKU_EVIDENCE_MAX_ITEMS = danmaku_analysis.DANMAKU_EVIDENCE_MAX_ITEMS
DANMAKU_LOCAL_BASELINE_EXCLUSION_SEC = danmaku_analysis.DANMAKU_LOCAL_BASELINE_EXCLUSION_SEC
DANMAKU_LOCAL_BASELINE_RADIUS_SEC = danmaku_analysis.DANMAKU_LOCAL_BASELINE_RADIUS_SEC
DANMAKU_MESSAGE_MAX_CHARS = danmaku_analysis.DANMAKU_MESSAGE_MAX_CHARS
_ASS_OVERRIDE_TAG_RE = danmaku_analysis._ASS_OVERRIDE_TAG_RE
_DANMAKU_BRACKET_EMOTE_RE = danmaku_analysis._DANMAKU_BRACKET_EMOTE_RE
_DANMAKU_GENERIC_REACTIONS = danmaku_analysis._DANMAKU_GENERIC_REACTIONS
_DANMAKU_PROMPT_INSTRUCTION_RE = danmaku_analysis._DANMAKU_PROMPT_INSTRUCTION_RE
_DANMAKU_TITLE_CUE_GROUPS = danmaku_analysis._DANMAKU_TITLE_CUE_GROUPS
_DANMAKU_TITLE_CUE_PRIORITY_PATTERNS = danmaku_analysis._DANMAKU_TITLE_CUE_PRIORITY_PATTERNS
_DANMAKU_UPOWER_RE = danmaku_analysis._DANMAKU_UPOWER_RE
DanmakuDensitySeries = danmaku_analysis.DanmakuDensitySeries
_normalise_danmaku_message = danmaku_analysis._normalise_danmaku_message
_display_danmaku_message = danmaku_analysis._display_danmaku_message
_is_question_only_danmaku = danmaku_analysis._is_question_only_danmaku
_danmaku_title_cue_messages = danmaku_analysis._danmaku_title_cue_messages
_danmaku_title_cue_groups_for_context = danmaku_analysis._danmaku_title_cue_groups_for_context
_danmaku_peak_content_evidence = danmaku_analysis._danmaku_peak_content_evidence
_format_danmaku_peak_content = danmaku_analysis._format_danmaku_peak_content
_danmaku_prompt_message_items = danmaku_analysis._danmaku_prompt_message_items
_density_percentile = danmaku_analysis._density_percentile
_danmaku_clip_threshold = danmaku_analysis._danmaku_clip_threshold
_median_number = danmaku_analysis._median_number
_danmaku_content_quality = danmaku_analysis._danmaku_content_quality
analyze_danmaku = danmaku_analysis.analyze_danmaku


# 人工时间轴兼容 façade：墙钟换算、分段过滤与 SRT 校准使用唯一实现。
MANUAL_TIMELINE_ALIGNMENT_MIN_SCORE = timeline_analysis.MANUAL_TIMELINE_ALIGNMENT_MIN_SCORE
MANUAL_TIMELINE_ALIGNMENT_SEARCH_SEC = timeline_analysis.MANUAL_TIMELINE_ALIGNMENT_SEARCH_SEC
MANUAL_TIMELINE_ALIGNMENT_STEP_SEC = timeline_analysis.MANUAL_TIMELINE_ALIGNMENT_STEP_SEC
MANUAL_TIMELINE_ALIGNMENT_WINDOW_SEC = timeline_analysis.MANUAL_TIMELINE_ALIGNMENT_WINDOW_SEC
MANUAL_TIMELINE_CHUNK_MARGIN_SEC = timeline_analysis.MANUAL_TIMELINE_CHUNK_MARGIN_SEC
MANUAL_TIMELINE_DIR = timeline_analysis.MANUAL_TIMELINE_DIR
MANUAL_TIMELINE_END_MARGIN_SEC = timeline_analysis.MANUAL_TIMELINE_END_MARGIN_SEC
MANUAL_TIMELINE_GROUNDING_MIN_SCORE = timeline_analysis.MANUAL_TIMELINE_GROUNDING_MIN_SCORE
MANUAL_TIMELINE_OPTIMIZATION_VERSION = timeline_analysis.MANUAL_TIMELINE_OPTIMIZATION_VERSION
MANUAL_TIMELINE_OPTIMIZE_GAP_SEC = timeline_analysis.MANUAL_TIMELINE_OPTIMIZE_GAP_SEC
MANUAL_TIMELINE_OPTIMIZE_MAX_GROUP_SEC = timeline_analysis.MANUAL_TIMELINE_OPTIMIZE_MAX_GROUP_SEC
_MANUAL_SEMANTIC_BIGRAM_STOPWORDS = timeline_analysis._MANUAL_SEMANTIC_BIGRAM_STOPWORDS
_MANUAL_SEMANTIC_GENERIC_TERMS = timeline_analysis._MANUAL_SEMANTIC_GENERIC_TERMS
_extract_video_start_datetime = timeline_analysis._extract_video_start_datetime
_manual_timeline_doc_candidates = timeline_analysis._manual_timeline_doc_candidates
_find_manual_timeline_doc = timeline_analysis._find_manual_timeline_doc
_read_docx_lines = timeline_analysis.read_docx_lines
_parse_manual_timeline_lines = timeline_analysis._parse_manual_timeline_lines
_parse_elapsed_timeline_report_lines = timeline_analysis._parse_elapsed_timeline_report_lines
_filter_manual_timeline_entries = timeline_analysis._filter_manual_timeline_entries
load_manual_timeline = timeline_analysis.load_manual_timeline
_manual_timeline_summary = timeline_analysis._manual_timeline_summary
_manual_alignment_text = timeline_analysis._manual_alignment_text
_manual_semantic_core = timeline_analysis._manual_semantic_core
_srt_alignment_windows = timeline_analysis._srt_alignment_windows
_align_manual_timeline_entries_to_srt = timeline_analysis._align_manual_timeline_entries_to_srt


# 标题兼容 façade：样式、证据绑定和多阶段复核只保留唯一实现。
MAX_PUBLISH_TITLE_CHARS = title_analysis.MAX_PUBLISH_TITLE_CHARS
MAX_TOPIC_TITLE_CHARS = title_analysis.MAX_TOPIC_TITLE_CHARS
TITLE_STYLE_EXAMPLE_LIMIT = title_analysis.TITLE_STYLE_EXAMPLE_LIMIT
TITLE_STYLE_PROFILE_PATH = title_analysis.TITLE_STYLE_PROFILE_PATH
_GENERIC_PUBLISH_TITLES = title_analysis._GENERIC_PUBLISH_TITLES
_GENERIC_TOPIC_TITLES = title_analysis._GENERIC_TOPIC_TITLES
_LEADING_ACCOUNT_PREFIX_RE = title_analysis._LEADING_ACCOUNT_PREFIX_RE
_META_TITLE_KEYWORDS = title_analysis._META_TITLE_KEYWORDS
_PLACEHOLDER_TITLES = title_analysis._PLACEHOLDER_TITLES
_PUBLISH_TITLE_META_KEYWORDS = title_analysis._PUBLISH_TITLE_META_KEYWORDS
_SUCCESSFUL_RAIL_EVIDENCE_RE = title_analysis._SUCCESSFUL_RAIL_EVIDENCE_RE
_TITLE_STYLE_TAG_KEYWORDS = title_analysis._TITLE_STYLE_TAG_KEYWORDS
_active_streamer_aliases = title_analysis._active_streamer_aliases
_build_title_style_prompt = title_analysis._build_title_style_prompt
_clean_topic_title = title_analysis._clean_topic_title
_clip_candidate_danmaku_prompt_evidence = title_analysis._clip_candidate_danmaku_prompt_evidence
_clip_candidate_reference_publish_titles = title_analysis._clip_candidate_reference_publish_titles
_compact_topic_phrase = title_analysis._compact_topic_phrase
_derive_topic_title = title_analysis._derive_topic_title
_fallback_publish_title = title_analysis._fallback_publish_title
_fallback_title_from_text = title_analysis._fallback_title_from_text
_is_bad_topic_title = title_analysis._is_bad_topic_title
_is_generic_topic_title = title_analysis._is_generic_topic_title
_is_incomplete_ai_title = title_analysis._is_incomplete_ai_title
_is_placeholder_title = title_analysis._is_placeholder_title
_load_title_style_profile = title_analysis.load_title_style_profile
_manual_title_from_text = title_analysis._manual_title_from_text
_normalise_obvious_report_terms = title_analysis._normalise_obvious_report_terms
_normalise_publish_title = title_analysis._normalise_publish_title
_normalise_title_hook = title_analysis._normalise_title_hook
_profile_formal_names = title_analysis._profile_formal_names
_prompt_context = title_analysis._prompt_context
_prompt_streamer_name = title_analysis._prompt_streamer_name
_publish_title_example = title_analysis._publish_title_example
_publish_title_instruction = title_analysis._publish_title_instruction
_publish_title_prefix = title_analysis._publish_title_prefix
_replace_streamer_role = title_analysis._replace_streamer_role
_sanitize_transport_claims = title_analysis._sanitize_transport_claims
_select_title_style_examples = title_analysis._select_title_style_examples
_specific_topic_phrase = title_analysis._specific_topic_phrase
_streamer_report_name = title_analysis._streamer_report_name
_streamer_role_pattern = title_analysis._streamer_role_pattern
_strip_body_prefix = title_analysis._strip_body_prefix
_strip_title_meta = title_analysis._strip_title_meta
_title_style_profile_path = title_analysis._title_style_profile_path
_final_title_review_payload = title_analysis._final_title_review_payload
_build_final_title_generation_prompt = title_analysis._build_final_title_generation_prompt
_normalise_final_title_option = title_analysis._normalise_final_title_option
_parse_final_title_candidates = title_analysis._parse_final_title_candidates
_build_final_title_judge_prompt = title_analysis._build_final_title_judge_prompt
_parse_final_title_judgement = title_analysis._parse_final_title_judgement
_review_selected_publish_titles = title_analysis.review_selected_publish_titles


# 候选兼容 façade：评分、价值复核和边界决策只保留唯一实现。
CHUNK_SEC = candidate_analysis.CHUNK_SEC
CLIP_MANUAL_REVIEW_MIN_STARS = candidate_analysis.CLIP_MANUAL_REVIEW_MIN_STARS
CLIP_MIN_INTEREST_SCORE = candidate_analysis.CLIP_MIN_INTEREST_SCORE
CLIP_REVIEW_BATCH_SIZE = candidate_analysis.CLIP_REVIEW_BATCH_SIZE
CLIP_REVIEW_POLICY_VERSION = candidate_analysis.CLIP_REVIEW_POLICY_VERSION
CLIP_REVIEW_RETRY_BATCH_SIZE = candidate_analysis.CLIP_REVIEW_RETRY_BATCH_SIZE
DANMAKU_WINDOW = danmaku_analysis.DANMAKU_WINDOW
DANMAKU_WINDOW_STEP = danmaku_analysis.DANMAKU_WINDOW_STEP
LLMProviderUnavailableError = candidate_analysis.LLMProviderUnavailableError
LLMStructuredOutputError = candidate_analysis.LLMStructuredOutputError
LLM_ANALYSIS_MODEL = candidate_analysis.LLM_ANALYSIS_MODEL
LLM_COMPACT_MAX_TOKENS = candidate_analysis.LLM_COMPACT_MAX_TOKENS
LLM_COMPACT_TEXT_CHARS = candidate_analysis.LLM_COMPACT_TEXT_CHARS
LLM_DEFAULT_CONCURRENCY = candidate_analysis.LLM_DEFAULT_CONCURRENCY
LLM_FULL_TEXT_CHARS = candidate_analysis.LLM_FULL_TEXT_CHARS
LLM_MAX_CONCURRENCY = candidate_analysis.LLM_MAX_CONCURRENCY
LLM_MAX_TOKENS = candidate_analysis.LLM_MAX_TOKENS
MANUAL_TIMELINE_OPTIMIZE_BATCH_SIZE = timeline_analysis.MANUAL_TIMELINE_OPTIMIZE_BATCH_SIZE
MANUAL_TIMELINE_TOPIC_POST_SEC = timeline_analysis.MANUAL_TIMELINE_TOPIC_POST_SEC
MANUAL_TIMELINE_TOPIC_PRE_SEC = timeline_analysis.MANUAL_TIMELINE_TOPIC_PRE_SEC
MAX_INITIAL_FAILED_CHUNKS = candidate_analysis.MAX_INITIAL_FAILED_CHUNKS
OUTRO_TRIGGER_JOIN_GAP_SEC = candidate_analysis.OUTRO_TRIGGER_JOIN_GAP_SEC
OUTRO_VARIANT_FAREWELL_AFTER_SEC = candidate_analysis.OUTRO_VARIANT_FAREWELL_AFTER_SEC
OUTRO_VARIANT_FAREWELL_BEFORE_SEC = candidate_analysis.OUTRO_VARIANT_FAREWELL_BEFORE_SEC
SC_CONTEXT_LOOKBACK_SEC = candidate_analysis.SC_CONTEXT_LOOKBACK_SEC
SC_FALLBACK_GIFT_LOOKBACK_SEC = candidate_analysis.SC_FALLBACK_GIFT_LOOKBACK_SEC
SC_TRIGGER_KEYWORDS = candidate_analysis.SC_TRIGGER_KEYWORDS
SRT_ESTIMATED_CHARS_PER_SEC = transcription_service.SRT_ESTIMATED_CHARS_PER_SEC
THANKS_TRIGGER_RE = candidate_analysis.THANKS_TRIGGER_RE
TOPIC_AI_FOCUS_EDGE_POST_CONTEXT_SEC = candidate_analysis.TOPIC_AI_FOCUS_EDGE_POST_CONTEXT_SEC
TOPIC_AI_FOCUS_EDGE_PRE_CONTEXT_SEC = candidate_analysis.TOPIC_AI_FOCUS_EDGE_PRE_CONTEXT_SEC
TOPIC_AI_FOCUS_NATURAL_POST_BOUNDARY_SEC = candidate_analysis.TOPIC_AI_FOCUS_NATURAL_POST_BOUNDARY_SEC
TOPIC_AI_FOCUS_NATURAL_PRE_BOUNDARY_SEC = candidate_analysis.TOPIC_AI_FOCUS_NATURAL_PRE_BOUNDARY_SEC
TOPIC_AI_FOCUS_POST_CONTEXT_SEC = candidate_analysis.TOPIC_AI_FOCUS_POST_CONTEXT_SEC
TOPIC_AI_FOCUS_PRE_CONTEXT_SEC = candidate_analysis.TOPIC_AI_FOCUS_PRE_CONTEXT_SEC
TOPIC_ANALYSIS_CHECKPOINT_VERSION = candidate_analysis.TOPIC_ANALYSIS_CHECKPOINT_VERSION
TOPIC_BOUNDARY_EVIDENCE_FORWARD_SEARCH_SEC = candidate_analysis.TOPIC_BOUNDARY_EVIDENCE_FORWARD_SEARCH_SEC
TOPIC_BOUNDARY_EVIDENCE_FORWARD_SEC = candidate_analysis.TOPIC_BOUNDARY_EVIDENCE_FORWARD_SEC
TOPIC_BOUNDARY_EVIDENCE_LOOKBACK_SEC = candidate_analysis.TOPIC_BOUNDARY_EVIDENCE_LOOKBACK_SEC
TOPIC_BOUNDARY_EVIDENCE_MIN_SCORE = candidate_analysis.TOPIC_BOUNDARY_EVIDENCE_MIN_SCORE
TOPIC_BOUNDARY_FORWARD_SHIFT_MAX_SEC = candidate_analysis.TOPIC_BOUNDARY_FORWARD_SHIFT_MAX_SEC
TOPIC_CONTEXT_GAP = transcription_service.TOPIC_CONTEXT_GAP
TOPIC_DIRECT_SLICE_MAX_SEC = candidate_analysis.TOPIC_DIRECT_SLICE_MAX_SEC
TOPIC_FOCUS_POST_SEC = candidate_analysis.TOPIC_FOCUS_POST_SEC
TOPIC_FOCUS_PRE_SEC = candidate_analysis.TOPIC_FOCUS_PRE_SEC
TOPIC_HARD_TRANSITION_GAP_SEC = candidate_analysis.TOPIC_HARD_TRANSITION_GAP_SEC
TOPIC_LEAD_IN_LOOKBACK_SEC = candidate_analysis.TOPIC_LEAD_IN_LOOKBACK_SEC
TOPIC_LEAD_IN_RECOVERY_MIN_SEC = candidate_analysis.TOPIC_LEAD_IN_RECOVERY_MIN_SEC
TOPIC_MAX_CLIP_SEC = candidate_analysis.TOPIC_MAX_CLIP_SEC
TOPIC_MAX_REPAIRED_REPORT_SEC = candidate_analysis.TOPIC_MAX_REPAIRED_REPORT_SEC
TOPIC_MIN_CLIP_SEC = candidate_analysis.TOPIC_MIN_CLIP_SEC
TOPIC_MIN_REPORT_SEC = candidate_analysis.TOPIC_MIN_REPORT_SEC
TOPIC_NATURAL_BOUNDARY_POST_MAX_SEC = candidate_analysis.TOPIC_NATURAL_BOUNDARY_POST_MAX_SEC
TOPIC_NATURAL_BOUNDARY_PRE_MAX_SEC = candidate_analysis.TOPIC_NATURAL_BOUNDARY_PRE_MAX_SEC
TOPIC_POST_CONTEXT_SEC = candidate_analysis.TOPIC_POST_CONTEXT_SEC
TOPIC_PRE_CONTEXT_SEC = candidate_analysis.TOPIC_PRE_CONTEXT_SEC
TOPIC_REFERENCE_END_TOLERANCE_SEC = candidate_analysis.TOPIC_REFERENCE_END_TOLERANCE_SEC
TOPIC_RELEVANT_CONTINUATION_GAP_SEC = candidate_analysis.TOPIC_RELEVANT_CONTINUATION_GAP_SEC
TOPIC_REQUIRED_CONTEXT_OVERFLOW_SEC = candidate_analysis.TOPIC_REQUIRED_CONTEXT_OVERFLOW_SEC
TOPIC_REVIEW_FOCUS_MAX_SEC = candidate_analysis.TOPIC_REVIEW_FOCUS_MAX_SEC
_BOUNDARY_EVIDENCE_STOP_TERMS = candidate_analysis._BOUNDARY_EVIDENCE_STOP_TERMS
_CIRCLED_NUMBERS = candidate_analysis._CIRCLED_NUMBERS
_DANMAKU_META_KEYWORDS = candidate_analysis._DANMAKU_META_KEYWORDS
_FRAGMENT_BODY_LINES = candidate_analysis._FRAGMENT_BODY_LINES
_HEADING_RE = candidate_analysis._HEADING_RE
_MANUAL_AI_PLACEHOLDER_PHRASES = candidate_analysis._MANUAL_AI_PLACEHOLDER_PHRASES
_META_BODY_KEYWORDS = candidate_analysis._META_BODY_KEYWORDS
_NEXT_CASE_ASR_TRIGGER_RE = candidate_analysis._NEXT_CASE_ASR_TRIGGER_RE
_NO_SLICE_HINTS = candidate_analysis._NO_SLICE_HINTS
_OUTRO_ACTIVITY_VARIANT_RE = candidate_analysis._OUTRO_ACTIVITY_VARIANT_RE
_OUTRO_FAREWELL_EVIDENCE = candidate_analysis._OUTRO_FAREWELL_EVIDENCE
_OUTRO_TRIGGER_NORMALISE_RE = candidate_analysis._OUTRO_TRIGGER_NORMALISE_RE
_TOPIC_CONCLUSION_RE = candidate_analysis._TOPIC_CONCLUSION_RE
_TOPIC_DECISION_EVIDENCE_RE = candidate_analysis._TOPIC_DECISION_EVIDENCE_RE
_TOPIC_DISCOURSE_CONTINUATION_RE = candidate_analysis._TOPIC_DISCOURSE_CONTINUATION_RE
_TOPIC_LEAD_IN_TRIGGER_RE = candidate_analysis._TOPIC_LEAD_IN_TRIGGER_RE
_TOPIC_REFUND_RE = candidate_analysis._TOPIC_REFUND_RE
_TOPIC_REVIEW_TRANSIENT_KEYS = candidate_analysis._TOPIC_REVIEW_TRANSIENT_KEYS
_TRIGGER_CONTEXT_TOPIC_RE = candidate_analysis._TRIGGER_CONTEXT_TOPIC_RE
_UNCUTTABLE_CONTENT_KEYWORDS = candidate_analysis._UNCUTTABLE_CONTENT_KEYWORDS
_UNSUPPORTED_AI_AUDIENCE_REACTION_RE = candidate_analysis._UNSUPPORTED_AI_AUDIENCE_REACTION_RE
_VISUAL_CASE_SHIFT_RE = candidate_analysis._VISUAL_CASE_SHIFT_RE
_VISUAL_REACTION_LEAD_IN_RE = candidate_analysis._VISUAL_REACTION_LEAD_IN_RE
_VISUAL_REVIEW_TOPIC_RE = candidate_analysis._VISUAL_REVIEW_TOPIC_RE
_analysis_topics_snapshot = candidate_analysis._analysis_topics_snapshot
_analyze_topic_chunks = candidate_analysis.analyze_topic_chunks
_append_clip_candidate_source = candidate_analysis._append_clip_candidate_source
_apply_danmaku_slice_decisions = candidate_analysis._apply_danmaku_slice_decisions
_apply_reviewed_slice_decisions = candidate_analysis._apply_reviewed_slice_decisions
_assign_reviewed_semantic_slice_window = candidate_analysis._assign_reviewed_semantic_slice_window
_assign_topic_slice_window = candidate_analysis._assign_topic_slice_window
_average_danmaku_density = danmaku_analysis._average_danmaku_density
_boundary_context_has_speech = candidate_analysis._boundary_context_has_speech
_boundary_context_is_relevant = candidate_analysis._boundary_context_is_relevant
_boundary_evidence_term_counts = candidate_analysis._boundary_evidence_term_counts
_boundary_evidence_text_is_relevant = candidate_analysis._boundary_evidence_text_is_relevant
_build_chunk_prompt = candidate_analysis._build_chunk_prompt
_build_clip_candidate_review_audit = candidate_analysis._build_clip_candidate_review_audit
_build_clip_candidate_review_prompt = candidate_analysis._build_clip_candidate_review_prompt
_build_manual_topic_enrichment_prompt = candidate_analysis._build_manual_topic_enrichment_prompt
_cap_expanded_clip_mark = candidate_analysis._cap_expanded_clip_mark
_capped_speech_chain_start = candidate_analysis._capped_speech_chain_start
_clean_ass_danmaku_text = danmaku_analysis._clean_ass_danmaku_text
_clean_body_content = candidate_analysis._clean_body_content
_clean_topics_for_report = candidate_analysis._clean_topics_for_report
_clip_context_requires_trigger = candidate_analysis._clip_context_requires_trigger
_clip_interest_reason = candidate_analysis._clip_interest_reason
_clip_manual_star_count = candidate_analysis._clip_manual_star_count
_clip_marks_from_topics = candidate_analysis._clip_marks_from_topics
_clip_review_candidate = candidate_analysis._clip_review_candidate
_clip_review_checkpoint_is_complete = candidate_analysis._clip_review_checkpoint_is_complete
_clip_review_checkpoint_matches_policy = candidate_analysis._clip_review_checkpoint_matches_policy
_clip_star_bonus_cap = candidate_analysis._clip_star_bonus_cap
_configured_llm_concurrency = candidate_analysis._configured_llm_concurrency
_danmaku_peak_features = danmaku_analysis._danmaku_peak_features
_danmaku_prompt_evidence = danmaku_analysis._danmaku_prompt_evidence
_danmaku_topic_alignment = candidate_analysis._danmaku_topic_alignment
_dedupe_clip_marks = candidate_analysis._dedupe_clip_marks
_detect_stream_outro_clip = candidate_analysis._detect_stream_outro_clip
_enrich_manual_topics_in_batches = candidate_analysis.enrich_manual_topics_in_batches
_enrich_manual_topics_with_llm = candidate_analysis.enrich_manual_topics_with_llm
_enriched_manual_topic_from_item = candidate_analysis._enriched_manual_topic_from_item
_expand_clip_mark_with_context = candidate_analysis._expand_clip_mark_with_context
_expand_clip_marks_with_context = candidate_analysis._expand_clip_marks_with_context
_extract_json_payload = candidate_analysis._extract_json_payload
_filter_unsupported_ai_points = candidate_analysis._filter_unsupported_ai_points
_find_next_topic_hard_end = candidate_analysis._find_next_topic_hard_end
_find_relevant_topic_context_end = candidate_analysis._find_relevant_topic_context_end
_find_relevant_topic_context_start = candidate_analysis._find_relevant_topic_context_start
_find_sc_context_start = candidate_analysis._find_sc_context_start
_find_topic_lead_in_start = candidate_analysis._find_topic_lead_in_start
_find_visual_reaction_context_start = candidate_analysis._find_visual_reaction_context_start
_fit_final_clip_to_safe_srt_boundaries = candidate_analysis._fit_final_clip_to_safe_srt_boundaries
_format_report_time = candidate_analysis._format_report_time
_format_topic_block = candidate_analysis._format_topic_block
_fresh_manual_topic_evidence = candidate_analysis._fresh_manual_topic_evidence
_gift_trigger_has_question_followup = candidate_analysis._gift_trigger_has_question_followup
_has_high_star_manual_evidence = candidate_analysis._has_high_star_manual_evidence
_has_outro_farewell_evidence = candidate_analysis._has_outro_farewell_evidence
_high_energy_danmaku_peaks = danmaku_analysis._high_energy_danmaku_peaks
_integer_clip_bounds_outside_subtitles = candidate_analysis._integer_clip_bounds_outside_subtitles
_is_content_cuttable_topic = candidate_analysis._is_content_cuttable_topic
_is_duplicate_topic = candidate_analysis._is_duplicate_topic
_is_explicit_sc_topic = candidate_analysis._is_explicit_sc_topic
_is_explicit_sc_trigger = candidate_analysis._is_explicit_sc_trigger
_is_generic_danmaku_reaction = danmaku_analysis._is_generic_danmaku_reaction
_is_manual_ai_placeholder = candidate_analysis._is_manual_ai_placeholder
_is_manual_merge_target = candidate_analysis._is_manual_merge_target
_is_meta_body_line = candidate_analysis._is_meta_body_line
_is_retryable_llm_error = candidate_analysis._is_retryable_llm_error
_is_slice_marked = candidate_analysis._is_slice_marked
_is_topic_in_chunk = candidate_analysis._is_topic_in_chunk
_json_can_slice = candidate_analysis._json_can_slice
_json_points_to_body = candidate_analysis._json_points_to_body
_load_repaired_srt_segments = transcription_service._load_repaired_srt_segments
_load_topic_analysis_checkpoint = candidate_analysis._load_topic_analysis_checkpoint
_looks_like_delayed_topic_conclusion = candidate_analysis._looks_like_delayed_topic_conclusion
_looks_like_discourse_continuation = candidate_analysis._looks_like_discourse_continuation
_looks_like_low_score_visual_case_shift = candidate_analysis._looks_like_low_score_visual_case_shift
_looks_like_next_case_transition = candidate_analysis._looks_like_next_case_transition
_looks_like_sc_or_gift_trigger = candidate_analysis._looks_like_sc_or_gift_trigger
_make_chunk = candidate_analysis._make_chunk
_make_fallback_topic_from_chunk = candidate_analysis._make_fallback_topic_from_chunk
_manual_alignment_score = timeline_analysis._manual_alignment_score
_manual_entry_matches_topic = candidate_analysis._manual_entry_matches_topic
_manual_entry_meaningfully_overlaps_topic = candidate_analysis._manual_entry_meaningfully_overlaps_topic
_manual_evidence_line = candidate_analysis._manual_evidence_line
_manual_review_anchor = candidate_analysis._manual_review_anchor
_manual_text_supports_candidate = timeline_analysis._manual_text_supports_candidate
_merge_expanded_clip_marks = candidate_analysis._merge_expanded_clip_marks
_merge_manual_timeline_topics = candidate_analysis.merge_manual_timeline_topics
_nearest_safe_srt_boundary = candidate_analysis._nearest_safe_srt_boundary
_next_report_topic_safe_boundary = candidate_analysis._next_report_topic_safe_boundary
_normalise_body_line = candidate_analysis._normalise_body_line
_normalise_boundary_evidence_text = candidate_analysis._normalise_boundary_evidence_text
_normalise_outro_trigger_text = candidate_analysis._normalise_outro_trigger_text
_normalise_streamer_terms = transcription_service._normalise_streamer_terms
_optimized_entry_semantic_text = candidate_analysis._optimized_entry_semantic_text
_outro_topic_from_mark = candidate_analysis._outro_topic_from_mark
_overlap_ratio = candidate_analysis._overlap_ratio
_parse_clip_interest_score = candidate_analysis._parse_clip_interest_score
_parse_clip_star_bonus = candidate_analysis._parse_clip_star_bonus
_parse_hms = timeline_analysis.parse_hms
_parse_json_topics_response = candidate_analysis._parse_json_topics_response
_parse_llm_response = candidate_analysis._parse_llm_response
_profile_identity_names = transcription_service.profile_identity_names
_profile_matches_streamer = transcription_service.profile_matches_streamer
_reconcile_topic_manual_evidence = candidate_analysis._reconcile_topic_manual_evidence
_refresh_natural_boundary_metadata = candidate_analysis._refresh_natural_boundary_metadata
_refresh_topic_danmaku_evidence = candidate_analysis._refresh_topic_danmaku_evidence
_repair_short_topic_end = candidate_analysis._repair_short_topic_end
_report_fact_lines = candidate_analysis._report_fact_lines
_resolve_reviewed_report_overlaps = candidate_analysis._resolve_reviewed_report_overlaps
_review_peak_selected_topics = candidate_analysis._review_peak_selected_topics
_reviewed_danmaku_ranking_score = danmaku_analysis._reviewed_danmaku_ranking_score
_reviewed_topic_has_required_interest = candidate_analysis._reviewed_topic_has_required_interest
_sanitize_optimized_manual_entry = candidate_analysis._sanitize_optimized_manual_entry
_score_boundary_evidence_text = candidate_analysis._score_boundary_evidence_text
_serialized_progress_callback = candidate_analysis._serialized_progress_callback
_short_llm_error = candidate_analysis._short_llm_error
_snap_clip_to_srt_segments = candidate_analysis._snap_clip_to_srt_segments
_split_chain_crossing_topic_end = candidate_analysis._split_chain_crossing_topic_end
_srt_video_duration = candidate_analysis._srt_video_duration
_strip_code_fence = candidate_analysis._strip_code_fence
_strip_prompt_time_labels = candidate_analysis._strip_prompt_time_labels
_subtitle_speech_chains = candidate_analysis._subtitle_speech_chains
_subtitle_text_size = transcription_service._subtitle_text_size
_text_len_for_timing = transcription_service._text_len_for_timing
_topic_analysis_prompt_fingerprint = candidate_analysis._topic_analysis_prompt_fingerprint
_topic_danmaku_reference_lines = candidate_analysis._topic_danmaku_reference_lines
_topic_index_label = candidate_analysis._topic_index_label
_topic_peak_candidates = candidate_analysis._topic_peak_candidates
_topic_peak_focus_window = candidate_analysis._topic_peak_focus_window
_topic_semantic_text = candidate_analysis._topic_semantic_text
_topic_srt_summary_lines = candidate_analysis._topic_srt_summary_lines
_topics_from_manual_timeline = candidate_analysis._topics_from_manual_timeline
_trim_report_topic_around_reviewed_topic = candidate_analysis._trim_report_topic_around_reviewed_topic
_validate_unmatched_manual_topics = candidate_analysis._validate_unmatched_manual_topics
_validated_ai_focus_range = candidate_analysis._validated_ai_focus_range
_write_clip_review_checkpoint = candidate_analysis.write_clip_review_checkpoint
_write_completed_clip_review_checkpoint = candidate_analysis._write_completed_clip_review_checkpoint
_write_topic_analysis_checkpoint = candidate_analysis._write_topic_analysis_checkpoint
chunk_srt = candidate_analysis.chunk_srt
fmt_time = candidate_analysis.fmt_time
parse_srt_segments = candidate_analysis.parse_srt_segments
parse_srt_text = candidate_analysis.parse_srt_text


# 报告兼容 façade：报告、整理包和精调清单只保留唯一实现。
LLM_MODEL = reporting_service.LLM_REVIEW_MODEL
DEFAULT_REFINEMENT_QUEUE_DIR = reporting_service.DEFAULT_REFINEMENT_QUEUE_DIR
_UNIFIED_REFINEMENT_QUEUE_LOCK = reporting_service._UNIFIED_REFINEMENT_QUEUE_LOCK
REFINEMENT_WORKFLOW_STEPS = reporting_service.REFINEMENT_WORKFLOW_STEPS
_GENERATED_REPORT_TOPIC_RE = reporting_service._GENERATED_REPORT_TOPIC_RE
_parse_generated_topic_report = reporting_service.parse_generated_topic_report
_strip_emoji_for_title = reporting_service._strip_emoji_for_title
_make_part_title = reporting_service._make_part_title
_group_topics_for_parts = reporting_service._group_topics_for_parts
_group_topics_by_hour = reporting_service._group_topics_by_hour
_topic_clip_filename = reporting_service.topic_clip_filename
_compatible_topic_clip_filenames = reporting_service.compatible_topic_clip_filenames
_synchronise_selected_topic_ranges = reporting_service.synchronise_selected_topic_ranges
_clip_subtitle_filename = reporting_service.clip_subtitle_filename
_resolve_clip_subtitle_source = reporting_service.resolve_clip_subtitle_source
_publish_title_report_lines = reporting_service.publish_title_report_lines
_artifact_bundle_layout = reporting_service.artifact_bundle_layout
_render_artifact_overview = reporting_service.render_artifact_overview
organize_existing_artifacts = reporting_service.organize_existing_artifacts
_build_refinement_manifest = reporting_service.build_refinement_manifest
_render_refinement_manifest_markdown = reporting_service.render_refinement_manifest_markdown
_unified_refinement_queue_paths = reporting_service._unified_refinement_queue_paths
_refinement_task_is_completed = reporting_service._refinement_task_is_completed
_unified_refinement_record = reporting_service._unified_refinement_record
_render_unified_refinement_queue_markdown = reporting_service.render_unified_refinement_queue_markdown
_upsert_unified_refinement_queue = reporting_service.upsert_unified_refinement_queue
_write_refinement_manifest_files = reporting_service.write_refinement_manifest_files
_update_refinement_manifest_after_slice = reporting_service.update_refinement_manifest_after_slice
_build_timeline_report = reporting_service.build_timeline_report


# 切片兼容 façade：容器策略、复用和 FFmpeg 命令只保留唯一实现。
_GENERATED_VIDEO_SUFFIX_PATTERN = slicing_service._GENERATED_VIDEO_SUFFIX_PATTERN
SLICE_DEFAULT_CONCURRENCY = slicing_service.SLICE_DEFAULT_CONCURRENCY
_GENERATED_TOPIC_TEMP_RE = slicing_service._GENERATED_TOPIC_TEMP_RE
SLICE_DURATION_TOLERANCE_SEC = slicing_service.SLICE_DURATION_TOLERANCE_SEC
SLICE_EXACT_SEEK_PREROLL_SEC = slicing_service.SLICE_EXACT_SEEK_PREROLL_SEC
_GENERATED_TOPIC_ARTIFACT_RE = slicing_service._GENERATED_TOPIC_ARTIFACT_RE
SLICE_MAX_CONCURRENCY = slicing_service.SLICE_MAX_CONCURRENCY
SLICE_INDEX_MIN_CLIPS = slicing_service.SLICE_INDEX_MIN_CLIPS
_validated_video_path = slicing_service.validate_video_path
_cleanup_stale_topic_clips = slicing_service.cleanup_stale_topic_clips
_format_ffmpeg_seconds = slicing_service.format_ffmpeg_seconds
_is_reusable_topic_clip = slicing_service.is_reusable_topic_clip
_reuse_compatible_topic_clip = slicing_service.reuse_compatible_topic_clip
_reuse_topic_clip_after_title_change = slicing_service.reuse_topic_clip_after_title_change
_preferred_slice_video_encoder_args = slicing_service.preferred_slice_video_encoder_args
_software_slice_video_encoder_args = slicing_service.software_slice_video_encoder_args
_configured_slice_concurrency = slicing_service.configured_slice_concurrency
_build_precise_slice_ffmpeg_command = slicing_service.build_precise_slice_ffmpeg_command
_prepare_seekable_slice_source = slicing_service.prepare_seekable_slice_source
_slice_from_marks_impl = slicing_service.slice_from_marks_impl
slice_from_marks = slicing_service.slice_from_marks


# 流水线兼容 façade：编排只保留 autoslice.pipeline 唯一实现。
_format_manual_entry_for_prompt = pipeline_service._format_manual_entry_for_prompt
_manual_timeline_info_for_chunk = pipeline_service._manual_timeline_info_for_chunk
_attach_manual_timeline_to_chunks = pipeline_service.attach_manual_timeline_to_chunks
_title_hook_prompt_guide = pipeline_service.title_hook_prompt_guide
_build_system_prompt = pipeline_service.build_system_prompt
subtitle_title_services = pipeline_service.subtitle_title_services
_try_enrich_manual_topics = pipeline_service.try_enrich_manual_topics
_optimized_manual_entries_from_topics = pipeline_service.optimized_manual_entries_from_topics
_optimized_entry_needs_retry = pipeline_service.optimized_entry_needs_retry
_topic_from_optimized_entry = pipeline_service.topic_from_optimized_entry
_batch_warning_text = pipeline_service._batch_warning_text
_retry_optimized_timeline_entries = pipeline_service.retry_optimized_timeline_entries
_optimize_manual_timeline = pipeline_service.optimize_manual_timeline
_optimized_timeline_paths = pipeline_service.optimized_timeline_paths
_write_optimized_timeline_files = pipeline_service.write_optimized_timeline_files
_load_optimized_timeline_artifact = pipeline_service.load_optimized_timeline_artifact
_prepare_optimized_manual_timeline = pipeline_service.prepare_optimized_manual_timeline
optimize_manual_timeline_for_video = pipeline_service.optimize_manual_timeline_for_video
_optimize_manual_timeline_for_video_impl = pipeline_service.optimize_manual_timeline_for_video_impl
_scaled_progress_callback = pipeline_service._scaled_progress_callback
_monotonic_progress_callback = pipeline_service._monotonic_progress_callback
run_pipeline = pipeline_service.run_pipeline
_run_pipeline_impl = pipeline_service.run_pipeline_impl
_manual_timeline_for_rebuilt_report = pipeline_service._manual_timeline_for_rebuilt_report
_warning_without_previous_clip_review = pipeline_service._warning_without_previous_clip_review
retry_clip_review_from_artifacts = pipeline_service.retry_clip_review_from_artifacts
_retry_clip_review_from_artifacts_impl = pipeline_service.retry_clip_review_from_artifacts_impl


# LLM 兼容 façade 必须与唯一 gateway 保持对象身份；本模块不得重新定义。
_LLMApiConfig = llm_gateway.LLMApiConfig
_call_compatible_api = llm_gateway.call_compatible_api
_infer_api_type = llm_gateway.infer_api_type
_infer_llm_api_type = llm_gateway.infer_api_type
_load_llm_api_config = llm_gateway.load_api_config
_normalise_api_config = llm_gateway.normalise_api_config
_normalise_llm_api_config = llm_gateway.normalise_api_config
_read_llm_json_config = llm_gateway.read_json_config
_read_json_config = llm_gateway.read_json_config
load_api_config = llm_gateway.load_api_config
LLMResponseTruncatedError = llm_gateway.LLMResponseTruncatedError
LLMResponseFormatError = llm_gateway.LLMResponseFormatError
_LLMProviderRetryCoordinator = llm_gateway.LLMProviderRetryCoordinator
_llm_response_has_complete_json = llm_gateway.response_has_complete_json
_decode_llm_response_json = llm_gateway.decode_response_json
_parse_openai_response = llm_gateway.parse_openai_response
_parse_anthropic_response = llm_gateway.parse_anthropic_response
call_llm = llm_gateway.call_llm
_llm_http_status = llm_gateway.llm_http_status
_is_provider_service_unavailable = llm_gateway.is_provider_service_unavailable
_call_llm_with_retry = llm_gateway.call_llm_with_retry


# ============================================================
# 配置
# ============================================================
LLM_RETRY_DELAYS = llm_gateway.DEFAULT_RETRY_DELAYS
LLM_PROVIDER_UNAVAILABLE_RETRY_DELAYS = (
    llm_gateway.DEFAULT_PROVIDER_UNAVAILABLE_RETRY_DELAYS
)
LLM_REQUEST_TIMEOUT = llm_gateway.DEFAULT_REQUEST_TIMEOUT
# 修改候选复核提示、标题证据或通过规则时必须递增，防止旧标题检查点被继续复用。
# 字幕工作台的“排除背景音”只处理用于识别的临时 WAV，不修改源视频音轨。
# 先抑制稳定噪声和低音量背景，再由可选 CAM++ 说话人聚类保留主要说话人。
# 当前默认字幕为剪映字号 20、描边 100。28 字会在 16:9 成片中直接越界，
# 因此工作 SRT 以 13 字为硬上限；最终 ASS 仍会按实际画布再做一次保险拆分。
# 只供修复历史“全文重复到逐字时间戳”的旧 SRT 使用。该路径需要较完整的
# 上下文来纠正跨词专名；最终成片仍会在 ASS 层按画布宽度安全拆分。


# 兼容旧测试和外部脚本对该变量的临时覆盖；生产任务优先读取当前主播配置。


# ============================================================
# Step 1: FunASR 自动转录 (复用 core.py 逻辑，降级到 CPU)
# ============================================================


# ============================================================
# Step 2: 弹幕密度分析
# ============================================================


# 高频问号或同义短句很容易占满代表弹幕，导致真正能解释爆点的视觉细节
# 到不了标题模型。这里按标题常见的信息类型各保留少量原文旁证。


# ============================================================
# Step 3: SRT 解析 + 分块
# ============================================================


# ============================================================
# Step 4: LLM 分析
# ============================================================


# ============================================================
# LLM 响应解析与去重
# ============================================================









# ============================================================
# 话题切片上下文扩展
# ============================================================


# ============================================================
# 逐话题时间轴报告格式化
# ============================================================


def main(argv=None):
    """运行兼容的单文件话题分析命令。"""

    import sys

    args = list(sys.argv[1:] if argv is None else argv)
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    if args:
        flv = args[0]
        ass = os.path.splitext(flv)[0] + ".ass"
        if not os.path.exists(ass):
            ass = None
        result = run_pipeline(flv, ass, progress_callback=lambda m, s, t: print(f"[{s}%] {m}"))
        print(f"\n报告: {result['md_path']}")
        print(f"切片标记: {len(result['clip_marks'])} 个")
        for cm in result['clip_marks'][:10]:
            print(f"  [{fmt_time(cm['start'])}-{fmt_time(cm['end'])}] {cm['title']}")
        return 0
    else:
        print("用法: python topic_engine.py <视频文件>")
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
