"""旧人工时间轴工作流路径的同对象兼容 façade。"""

from autoslice.analysis.manual import workflow as _owner

FACADE_EXPORTS = _owner.FACADE_EXPORTS
format_manual_entry_for_prompt = _owner.format_manual_entry_for_prompt
manual_timeline_info_for_chunk = _owner.manual_timeline_info_for_chunk
attach_manual_timeline_to_chunks = _owner.attach_manual_timeline_to_chunks
try_enrich_manual_topics = _owner.try_enrich_manual_topics
optimized_manual_entries_from_topics = _owner.optimized_manual_entries_from_topics
optimized_entry_needs_retry = _owner.optimized_entry_needs_retry
topic_from_optimized_entry = _owner.topic_from_optimized_entry
batch_warning_text = _owner.batch_warning_text
retry_optimized_timeline_entries = _owner.retry_optimized_timeline_entries
optimize_manual_timeline = _owner.optimize_manual_timeline
