"""旧人工时间轴路径的同对象兼容 façade。"""

from autoslice.analysis.manual import timebase as _owner

FACADE_EXPORTS = _owner.FACADE_EXPORTS
TIMELINE_DIR = _owner.TIMELINE_DIR
MANUAL_TIMELINE_DIR = _owner.MANUAL_TIMELINE_DIR
MANUAL_TIMELINE_CHUNK_MARGIN_SEC = _owner.MANUAL_TIMELINE_CHUNK_MARGIN_SEC
MANUAL_TIMELINE_TOPIC_PRE_SEC = _owner.MANUAL_TIMELINE_TOPIC_PRE_SEC
MANUAL_TIMELINE_TOPIC_POST_SEC = _owner.MANUAL_TIMELINE_TOPIC_POST_SEC
MANUAL_TIMELINE_END_MARGIN_SEC = _owner.MANUAL_TIMELINE_END_MARGIN_SEC
MANUAL_TIMELINE_OPTIMIZE_GAP_SEC = _owner.MANUAL_TIMELINE_OPTIMIZE_GAP_SEC
MANUAL_TIMELINE_OPTIMIZE_MAX_GROUP_SEC = _owner.MANUAL_TIMELINE_OPTIMIZE_MAX_GROUP_SEC
MANUAL_TIMELINE_OPTIMIZE_BATCH_SIZE = _owner.MANUAL_TIMELINE_OPTIMIZE_BATCH_SIZE
MANUAL_TIMELINE_OPTIMIZATION_VERSION = _owner.MANUAL_TIMELINE_OPTIMIZATION_VERSION
MANUAL_TIMELINE_ALIGNMENT_SEARCH_SEC = _owner.MANUAL_TIMELINE_ALIGNMENT_SEARCH_SEC
MANUAL_TIMELINE_ALIGNMENT_WINDOW_SEC = _owner.MANUAL_TIMELINE_ALIGNMENT_WINDOW_SEC
MANUAL_TIMELINE_ALIGNMENT_STEP_SEC = _owner.MANUAL_TIMELINE_ALIGNMENT_STEP_SEC
MANUAL_TIMELINE_ALIGNMENT_MIN_SCORE = _owner.MANUAL_TIMELINE_ALIGNMENT_MIN_SCORE
MANUAL_TIMELINE_GROUNDING_MIN_SCORE = _owner.MANUAL_TIMELINE_GROUNDING_MIN_SCORE
parse_hms = _owner.parse_hms

_TIMELINE_ACCOUNT_PREFIX_RE = _owner._TIMELINE_ACCOUNT_PREFIX_RE
_MANUAL_SEMANTIC_GENERIC_TERMS = _owner._MANUAL_SEMANTIC_GENERIC_TERMS
_MANUAL_SEMANTIC_BIGRAM_STOPWORDS = _owner._MANUAL_SEMANTIC_BIGRAM_STOPWORDS
extract_video_start_datetime = _owner.extract_video_start_datetime
manual_timeline_doc_candidates = _owner.manual_timeline_doc_candidates
find_manual_timeline_doc = _owner.find_manual_timeline_doc
read_docx_lines = _owner.read_docx_lines
parse_manual_timeline_lines = _owner.parse_manual_timeline_lines
parse_elapsed_timeline_report_lines = _owner.parse_elapsed_timeline_report_lines
filter_manual_timeline_entries = _owner.filter_manual_timeline_entries
load_manual_timeline = _owner.load_manual_timeline
manual_timeline_summary = _owner.manual_timeline_summary
manual_alignment_text = _owner.manual_alignment_text
manual_alignment_score = _owner.manual_alignment_score
manual_semantic_core = _owner.manual_semantic_core
manual_text_supports_candidate = _owner.manual_text_supports_candidate
srt_alignment_windows = _owner.srt_alignment_windows
align_manual_timeline_entries_to_srt = _owner.align_manual_timeline_entries_to_srt

_extract_video_start_datetime = extract_video_start_datetime
_manual_timeline_doc_candidates = manual_timeline_doc_candidates
_find_manual_timeline_doc = find_manual_timeline_doc
_parse_manual_timeline_lines = parse_manual_timeline_lines
_parse_elapsed_timeline_report_lines = parse_elapsed_timeline_report_lines
_filter_manual_timeline_entries = filter_manual_timeline_entries
_manual_timeline_summary = manual_timeline_summary
_manual_alignment_text = manual_alignment_text
_manual_alignment_score = manual_alignment_score
_manual_semantic_core = manual_semantic_core
_manual_text_supports_candidate = manual_text_supports_candidate
_srt_alignment_windows = srt_alignment_windows
_align_manual_timeline_entries_to_srt = align_manual_timeline_entries_to_srt
